#!/usr/bin/env python3
"""completion.py — shell completion for the CLI, derived from the parser rather than written by hand.

WHY THIS EXISTS
---------------
Both reference agents ship this. Reasonix has `reasonix completion bash|zsh|fish`; Kimi leans on the
same idea through its own shell integration. A forty-subcommand CLI where the only way to learn a
verb is to read `--help` is a CLI people use two commands of.

WHY IT IS DERIVED
-----------------
A completion script is a *second copy of the command tree* unless it is generated from the tree
itself, and a second copy goes stale the moment a verb is renamed. The failure is quiet and specific:
the shell offers `system consent grant` long after it was removed, or silently stops offering a verb
that works — and because completion is advisory, nothing ever errors. So every name below is read off
`argparse`'s own actions, walking nested subparsers recursively. There is no list to forget to update.

The walk is the same technique `engine.systemcli._command_names` uses for its shorthand resolution;
that module scans to decide how to re-parse argv, this one scans to describe the tree to a shell.
"""

from __future__ import annotations

import argparse
from typing import Any, Iterator

__all__ = ["SUPPORTED_SHELLS", "script_for", "command_tree", "top_level_names"]

#: The shells this module can emit for. Named here so the CLI's `choices=` and this list cannot drift.
SUPPORTED_SHELLS: tuple[str, ...] = ("bash", "zsh", "fish")


def _subparsers_of(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    """The subcommands of one parser, as name -> parser.

    `argparse` keeps these on a private `_SubParsersAction`, and there is no public accessor — the
    same constraint `systemcli._command_names` documents. Reading the private attribute is preferable
    to maintaining a registry alongside the parser, because the registry is the thing that rots.
    """
    found: dict[str, argparse.ArgumentParser] = {}
    for action in parser._actions:  # noqa: SLF001 - argparse exposes no public accessor
        choices = getattr(action, "choices", None)
        if isinstance(choices, dict):
            for name, sub in choices.items():
                if isinstance(sub, argparse.ArgumentParser):
                    found[str(name)] = sub
    return found


def top_level_names(parser: argparse.ArgumentParser) -> list[str]:
    """The commands a person can type first. Sorted, because shell output order is the reader's."""
    return sorted(_subparsers_of(parser))


def command_tree(parser: argparse.ArgumentParser, prefix: tuple[str, ...] = ()) -> list[tuple[str, ...]]:
    """Every command path in the tree, as tuples — `("system", "consent", "grant")` for the leaf.

    Paths rather than a flat set of words, because a shell completes *positionally*: offering `grant`
    after any first word would suggest `engine.cli run grant`, which does not exist. Only the names
    that are legal at the position the person is typing belong in the candidate list.
    """
    paths: list[tuple[str, ...]] = []
    for name, sub in sorted(_subparsers_of(parser).items()):
        path = (*prefix, name)
        paths.append(path)
        paths.extend(command_tree(sub, path))
    return paths


def _option_strings(parser: argparse.ArgumentParser) -> Iterator[str]:
    """Every `--flag` and `-f` a parser accepts, including inherited parents.

    Inherited matters: `common` is passed as a parent to nearly every subparser, so a walk that read
    only a parser's own actions would omit `--json` and `--project` exactly where they are most used.
    """
    seen: set[str] = set()
    for action in parser._actions:  # noqa: SLF001
        for option in action.option_strings:
            if option not in seen:
                seen.add(option)
                yield option


def _bash(program: str, tree: list[tuple[str, ...]], options: str) -> str:
    """A bash completion script.

    The command word lists are emitted as literal strings rather than computed at completion time.
    Computing them would mean re-running Python on every TAB press, which is the difference between a
    completion that feels instant and one people turn off.
    """
    words = " ".join(sorted({path[-1] for path in tree} | {path[0] for path in tree}))
    first = " ".join(top_level_names_from(tree))
    return f"""# {program} completion for bash — generated by `{program} completion bash`.
# Derived from the parser, so a renamed subcommand cannot be offered after it is gone.
# Install:  {program} completion bash > /etc/bash_completion.d/{program}
#       or: source <({program} completion bash)
_{program}_complete() {{
    local cur prev words
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"

    # The first word after the program name is a top-level command; after that, any known subcommand
    # name. A full positional walk is deliberately not attempted: bash's completion protocol makes it
    # awkward, and the cost of a slightly over-eager suggestion is far lower than the cost of a stale
    # hand-written list.
    # A flag is tried first, at every position. The order matters: checking the position first meant
    # `engine.cli --js<TAB>` completed to *nothing*, because the top-level branch returns the command
    # list before the `-*` arm is ever reached — so the global flags, which are the thing a person
    # most wants completed, were the one thing that could not be. Found by running the script rather
    # than reading it.
    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $(compgen -W "{options}" -- "$cur") )
        return 0
    fi

    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "{first}" -- "$cur") )
        return 0
    fi

    COMPREPLY=( $(compgen -W "{words}" -- "$cur") )
    return 0
}}
complete -F _{program}_complete {program}
"""


def _zsh(program: str, tree: list[tuple[str, ...]]) -> str:
    """A zsh completion script using the modern `_arguments`-free describe form.

    zsh is given the tree in full — `path:description` pairs at the right depth — because its
    completion system is positional and can use that properly, unlike bash's word list.
    """
    lines: list[str] = []
    for path in sorted(tree):
        parent = " ".join(path[:-1]) if len(path) > 1 else ""
        lines.append(f"        '{path[-1]}:{parent or 'command'}' \\")
    body = "\n".join(lines).rstrip(" \\")
    return f"""#compdef {program}
# {program} completion for zsh — generated by `{program} completion zsh`.
# Derived from the parser, so a renamed subcommand cannot be offered after it is gone.
# Install:  {program} completion zsh > "${{fpath[1]}}/_{program}"
_{program}() {{
    local -a commands
    commands=(
{body}
    )
    _describe 'command' commands
}}
_{program} "$@"
"""


def _fish(program: str, tree: list[tuple[str, ...]]) -> str:
    """A fish completion script.

    Fish wants one line per completable name with a condition, which is why each path is emitted
    separately rather than as a shared word list: fish can express "only offer this at depth N", and
    suppressing a wrong suggestion is worth the extra lines.
    """
    out = [f"# {program} completion for fish — generated by `{program} completion fish`.",
           f"# Install: {program} completion fish > ~/.config/fish/completions/{program}.fish"]
    for path in sorted(tree):
        condition = (f"__fish_seen_subcommand_from {path[-2]}"
                     if len(path) > 1 else "not __fish_seen_subcommand_from")
        out.append(f"complete -c {program} -n '{condition}' -a '{path[-1]}'")
    return "\n".join(out) + "\n"


def top_level_names_from(tree: list[tuple[str, ...]]) -> list[str]:
    """Top-level names recovered from the path list, so `_bash` needs no second walk of the parser."""
    return sorted({path[0] for path in tree})


def script_for(shell: str, parser: argparse.ArgumentParser, *, program: str = "engine.cli") -> str:
    """The completion script for `shell`. Raises `ValueError` for a shell that is not supported.

    `program` defaults to the module invocation this repo actually documents (`python3 -m engine.cli`),
    and is a parameter so a packaged entry point can name itself without a second implementation.
    """
    name = str(shell or "").strip().lower()
    if name not in SUPPORTED_SHELLS:
        raise ValueError(f"unsupported shell {shell!r}; choose one of {', '.join(SUPPORTED_SHELLS)}")
    tree = command_tree(parser)
    if name == "bash":
        return _bash(program, tree, " ".join(sorted(_option_strings(parser))))
    if name == "zsh":
        return _zsh(program, tree)
    return _fish(program, tree)
